default:
  aws_access_key_id: 'AKIAURBVRMIEF6VTFMWI'     # required
  aws_secret_access_key: '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' # required
  region: 'us-east-1'          # optional, defaults to 'us-east-1'
