default:
  aws_access_key_id: 'AKIAURBVRMIEFDYQ77IF'     # required
  aws_secret_access_key: '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' # required
  region: 'us-east-1'          # optional, defaults to 'us-east-1'
